### ISSUE TITLE
Screen record

### ISSUE THREAD

**Issue by Dhalian** [Core-2-Extreme/Video_player_for_3DS#1]
Is the ScreenRecording will be working soon ? Thx in Advance.

**Comment by Core-2-Extreme** [comment]
Screen recording is available now(but no sound and low framerate).
File will be saved to sdmc:/Video_player/screen_recording/

**Comment by Dhalian** [comment]
> Screen recording is available now(but no sound and low framerate).
> File will be saved to sdmc:/Video_player/screen_recording/

I have an Arm11 Error when i try to use it

**Comment by Core-2-Extreme** [comment]
What console are you using?
Is it old3ds?

**Comment by Dhalian** [comment]
> What console are you using?
> Is it old3ds?

I was using New 2DS xl, but i fixed the problem

**Comment by Core-2-Extreme** [comment]
What was cause?
