### ISSUE TITLE
Broken high resolution mode on old 2DS

### ISSUE THREAD

**Issue by windows-server-2003** [Core-2-Extreme/Video_player_for_3DS#10]
Old 2DS doesn't support doubled resolution mode, so the top screen would look like the image below with the feature enabled.
This option should be grayed out in the settings menu on old 2DSes.
New 2DS seems to support it for some reason. (refer to https://libctru.devkitpro.org/gfx_8h.html#a1ffe33f6b3e9a61ee916997fc6cf6ace)

![2021-06-29_17-04-23 775_top](https://user-images.githubusercontent.com/31173797/123761099-7454ba00-d8fc-11eb-803a-a298ead286ff.png)

**Comment by Core-2-Extreme** [comment]
I'll fix it.
