### ISSUE TITLE
error when building 

### ISSUE THREAD

**Issue by techno-arch** [Core-2-Extreme/Video_player_for_3DS#13]
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `mkdir -p (1)/Video_player_for_3DS-main/build'
make: *** [Makefile:232: (1)/Video_player_for_3DS-main/build] Error 2
Press any key to rebuild.

**Comment by Core-2-Extreme** [comment]
Where do you put video player for 3ds folder?
Give me full path.
e.g.

`C:\Users\cache\Documents\GitHub\Video_player_for_3DS`

**Comment by techno-arch** [comment]
C:\Users\username\Downloads\New folder (7)\Video_player_for_3DS-main
when running the bat file as admin it says
make: *** No rule to make target 'all_win'.  Stop.

**Comment by Core-2-Extreme** [comment]
C:\Users\username\Downloads\ **New folder (7)** \Video_player_for_3DS-main
is problem, rename it to something like New_folder_7 (no `space`, `(` and `)` )

**Comment by techno-arch** [comment]
thank you
