### ISSUE TITLE
Screen Recording does not work

### ISSUE THREAD

**Issue by FoxbitDreamtail** [Core-2-Extreme/Video_player_for_3DS#18]
whenever I go to the screen recording tab and choose any of the 3 options(with the LCD setting set from 800px to none) it crashes my New 3DS XL entirely. Luma bluescreen with the error Data Abort(
![20210801_210155 1](https://user-images.githubusercontent.com/71094975/127794972-da22eb70-2087-49d7-a6f1-23fa0e484351.jpg))

**Comment by Core-2-Extreme** [comment]
Are you using .cia or .3dsx?
And what version?

**Comment by FoxbitDreamtail** [comment]
.cia and latest downloaded from Universal updater, confirmed latest by this repository.

**Comment by FoxbitDreamtail** [comment]
Apparently just have to close the software and save settings, I failed to do this. Sorry for wasting your time.
