### ISSUE TITLE
request for aditions to the screen record feature

### ISSUE THREAD

**Issue by FoxbitDreamtail** [Core-2-Extreme/Video_player_for_3DS#19]
The title really explains it but it would be nice if the screen record feature could record the screen after the application is closed and then whenever you go back into it you can end the recording and then send it to something like a laptop for editing and posting to something like YouTube. Would this be possible? I was thinking something like NTR CFW does...

**Comment by Mewthree3** [comment]
Would that really be under the app’s specs tho? This is a video player after all. Who knows maybe coreさん can work his magic and somehow implement screen recording heh

**Comment by FoxbitDreamtail** [comment]
I mean, it kinda already records in-app so O dont see why not try and port it to elseware like minecraft (namely because it is completly incompatable with NTR CFW.

**Comment by Core-2-Extreme** [comment]
It is not possible because all threads and memory will be freed after app exit.
Maybe I have to run other background process but I don't know how.
If I found solution I'll create separate app(like screen recorder for 3DS) not in this app.
