### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by dixy52-beep** [Core-2-Extreme/Video_player_for_3DS#2]
I would really love to help you in this project (sorry if I write it in issues but I don't know where to say it otherwise) I made a logo for your app and would also love to make a banner for you. Do you have a discord or something?
My logo here 
https://www.dropbox.com/s/uyobhpx80hvvf2i/logomadebyme.png?dl=0

**Comment by Core-2-Extreme** [comment]
Thank you for your icon I'll use it next version.
My discord account is ARM11#7410
