### ISSUE TITLE
request for the ability to make injects of videos at compilation of cia  

### ISSUE THREAD

**Issue by techno-arch** [Core-2-Extreme/Video_player_for_3DS#22]
make it so you can bundle the player into a cia file with a video file like you can with virtual console games (but with games). they have methods to do so already however they both use their own video codecs that are not as good as h264 and h265.

**Comment by Core-2-Extreme** [comment]
You can bundle your video by putting videos in `romfs/` but I think in order to play video, you need to move it to sd card before playing it.
