### ISSUE TITLE
Player freezes after playing 3 seconds of H.264 or H.265 MP4 video

### ISSUE THREAD

**Issue by iAmInActions** [Core-2-Extreme/Video_player_for_3DS#25]
I used ffmpeg to convert video to a suitable format that I thought would run well on the 3ds but first I did not get any audio and second the entire player froze after 3 seconds of playback and would not respond. This issue could be reproduced by restarting the 3ds and selecting the same mp4 file again.

ffmpeg commands used (in this order):

ffmpeg -i "$HOME/Video/BigBuckBunny720p30.mp4" -profile:v baseline -preset fast -vf scale=120:72 -vcodec libx264 -vcodec libx264 -crf 24 -acodec aac -b:a 64K "/tmp/tmp-bbb.mp4"

ffmpeg -i "/tmp/tmp-bbb.mp4" -filter:v fps=15 "/mnt/3DS/Video_player/bbb.mp4"

**Comment by Core-2-Extreme** [comment]
Check if ndspinit() is 0x0
[How to check ndsp](https://drive.google.com/file/d/1ZAioYw_DEG2tXYxm6QOZ2dmeb9XP5MY2/view)
If not 0x0, run [dsp1](https://github.com/zoogie/DSP1/releases) then try again.
