### ISSUE TITLE
800px mode

### ISSUE THREAD

**Issue by RocketRobz** [Core-2-Extreme/Video_player_for_3DS#3]
Since this apparently supports videos around 800px horizontally, it would be great if this has 800px mode implemented, in order to achieve a high image quality.

**Comment by Core-2-Extreme** [comment]
![00000026](https://user-images.githubusercontent.com/45873899/113524413-781cbd00-95e9-11eb-9596-3b3017ea48c3.jpg)
There is high resolution mode.

**Comment by RocketRobz** [comment]
Oh, there is?
When is it activated in the code?

**Comment by Core-2-Extreme** [comment]
here
https://github.com/Core-2-Extreme/Video_player_for_3DS/blob/main/source/system/draw/draw.cpp#L578

**Comment by RocketRobz** [comment]
Thank you!
