### ISSUE TITLE
The video freezes after 3 seconds of playback

### ISSUE THREAD

**Issue by JustScratchCoder** [Core-2-Extreme/Video_player_for_3DS#31]
After the New update i opened up the player selected a video. And after 3 seconds it froze. Is there anything i can do?

**Comment by Core-2-Extreme** [comment]
Does `it froze` mean entire application freeze or only playback?
Does it happen to all video?
Did you hear any audio before playback stop?

**Comment by JustScratchCoder** [comment]
Yes i did hear heard audio before the PLAYBACK froze. the player didn`t. when i tried to load another video it didn`t work.

**Comment by JustScratchCoder** [comment]
Here is a video of the "malfunction"
https://youtu.be/8sEGxQoODzM

**Comment by Core-2-Extreme** [comment]
ok, could you do and record following step?

Before playing your video, press Y button and tap on right bottom tab(above "controls" button) to display debug graph, then play your video.
After playback stopped, press START button to back menu(not nintendo's home menu) then press SELECT button to display debug log(you can move debug logs with circle pad).

**Comment by JustScratchCoder** [comment]
okey

**Comment by JustScratchCoder** [comment]
https://youtu.be/CbQILEH1oqA
I noticed that the video stops randomly. maybe it depends on something.... idk actually.
but here i did the steps you sended

**Comment by Core-2-Extreme** [comment]
Well, turn multi-threaded decoding off and try again.
If it won't help turn hardware color conversion off as well.

Some `avcodec_recieve_frame() failed -11 0xfffffffa` is expected behavior if video contains B-frames.

**Comment by JustScratchCoder** [comment]
Thank You!  It Worked. The Multi Threaded Decoding was the problem!
 
I will comment if something is wrong

**Comment by Core-2-Extreme** [comment]
ok, something went wrong in multi-threaded decoding, thank you for reporting bugs.
