### ISSUE TITLE
Cannot Scroll through file explorer.

### ISSUE THREAD

**Issue by JustScratchCoder** [Core-2-Extreme/Video_player_for_3DS#36]
When i installed the newest update, when wanting to play a video, i could not scroll through the files, there was only the (move to parent directory) (dir), by clicking this option, there was only Unknown directories. 

Here`s a video of the error:
https://youtu.be/UnuujgYw8sE

EDIT:
when looking in the logs it says:
[Expl/Read dir thread] Util_file_read_dir()...[Error]Out of memory. 0xfffffffe

**Comment by Core-2-Extreme** [comment]
I think you have too much file in the same directory.
Try this one
[Video_player_for_3DS.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/7697889/Video_player_for_3DS.zip)
I just changed maximum number of file in the same directory.

**Comment by JustScratchCoder** [comment]
Yes it helped, i may had too much files in the root directory! i`l try to categorize my files. thank you!

**Comment by Core-2-Extreme** [comment]
You're welcome.

Increasing maximum files didn't consume too much memory so I'll change maximum files in the directory from 256 to 1024 in next release.
