### ISSUE TITLE
Audio: No audio on surround tracks

### ISSUE THREAD

**Issue by moisespr123** [Core-2-Extreme/Video_player_for_3DS#37]
```
ffmpeg -i {input} -c:v h264_nvenc -preset slow -c:a libfdk_aac -b:a 256K -af "volume=4" -bf 0 -g 48 -ac 2 {output}
```

At lease using ffmpeg, by default it will encode all audio channels unless the `-ac 2` argument is passed to encode the audio as a stereo track. If I forget to use it, the resulting video file will play without audio.

Not sure if it's a bug or if the player expects it to be a stereo track, in which case, please ignore this. Just posting about this finding.

**Comment by Core-2-Extreme** [comment]
Yes, the player expected mono (-ac 1) or stereo (-ac 2) audio only.
But thank you for reporting it I added error message for it.
