### ISSUE TITLE
Video: Seeking issues if MKV container is used

### ISSUE THREAD

**Issue by moisespr123** [Core-2-Extreme/Video_player_for_3DS#38]
```
ffmpeg -i {input} -c:v h264_nvenc -preset slow -c:a libfdk_aac -b:a 256K -af "volume=4" -bf 0 -g 48 -ac 2 {output.mkv}
```

The above command line will work. Seeking via the touch screen actually works and is way faster than when the container is `.mp4`.

The real issue here is that using the D-Pad doesn't work correctly. Going back actually goes forward and it seems to jump to a farther point as the video progresses. It only seems to work at the very first minutes of a video file.

The seeking issue doesn't happen on .mp4 files produced with the same command line but of course, changing the output container to .mp4.

**Comment by Core-2-Extreme** [comment]
I used your command (used `-c:a aac ` instead of `-c:a libfdk_aac` because my ffmpeg doesn't have it) to encode the video.
Unfortunately, I couldn't reproduce it.

Are you using hardware decoder or software decoder?
Could you provide your video(output.mkv not input) if possible?

**Comment by moisespr123** [comment]
It happens on both. Be sure to use a long video (Maybe an hour long) and seek starting at the middle. It may work fine at the beginning but then will skip.

I'm using nightly ffmpeg builds built using [Media Autobuild Suite](https://github.com/m-ab-s/media-autobuild_suite) on Windows.

Which video codec did you use? Maybe it could be related to that? The issue doesn't happen on mp4 files.

**Comment by Core-2-Extreme** [comment]
I used `h264_nvenc` and video was 2 hours long.

https://user-images.githubusercontent.com/45873899/147877185-b1041dd7-0bdc-4026-b98e-e9ed97abd686.mp4

**Comment by moisespr123** [comment]
I tried using MKV again and can no longer reproduce this issue. Seems to be fixed on my side using the latest video player version and latest ffmpeg.
