### ISSUE TITLE
Exception when playing video

### ISSUE THREAD

**Issue by adryzz** [Core-2-Extreme/Video_player_for_3DS#39]
Alright, so i took an H265 10bit anime episode and transcoded it so that it would be easier to play back by my O3DS XL.

```ffmpeg -i episode.mkv -c:v scale=400:240, libx264 -preset placebo -t 20 output1.mp4```
(scale to 400x240, use H264 preset placebo and only include the first 20 seconds)

But when i try to play it back, the application throws an exception and the console crashes.

(had to zip the dump because github doesnt like .dmp files)
[crash_dump_00000023.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/7774863/crash_dump_00000023.zip)

the video
[output1.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/7774868/output1.zip)

**Comment by Core-2-Extreme** [comment]
Currently, video player only support `yuv420p` pixel format so encode your video with `-pix_fmt yuv420p`.
Your command line would be `ffmpeg -i episode.mkv -c:v scale=400:240, libx264 -preset placebo -t 20 -pix_fmt yuv420p output1.mp4`

note : O3DS does not have enough power to decode h264 240p video.
If you want to use h264, downscale around 144p or use older codec such as mpeg2video, mpeg1video
