### ISSUE TITLE
Add to the app store

### ISSUE THREAD

**Issue by Pysis868** [Core-2-Extreme/Video_player_for_3DS#4]
Can be found here: https://apps.fortheusers.org/3ds

For submitted, seems the usual process is not recommended, like here: https://submit.fortheusers.org/

For 3DS homebrew apps, they want PRs here instead: https://github.com/CrafterPika/3ds-homebrew

**Comment by Dhalian** [comment]
Why not purpose to Universal-Team to add it into the Universal-DB Store of the Universal-Updater

**Comment by Pysis868** [comment]
Because I've used it, and this one seems most popular, populated, searchable, mature, supported, nice community, used primarily on / common to other platforms, and I've never heard of the other one.

I know of their efforts supporting Switch and Wii U already, and wanting to grow to other platforms like 3DS and Wii.  For example, when searching the internet and providing enough keywords not to get first-party results that I would better describe as "eShop":

https://duckduckgo.com/?q=switch+homebrew+app+store&t=ffab&atb=v245-1&ia=web
 -  https://www.homebrewgeneral.net/2019/06/switch-homebrew-appstore.html
 -  https://www.cfwaifu.com/switch-hb-appstore/
 -  https://github.com/fortheusers/hb-appstore/releases
 -  https://apps.fortheusers.org/
 -  https://www.switchbru.com/appstore/
 -  https://gbatemp.net/threads/switch-homebrew-appstore.493086/
 -  https://www.dekazeta.net/foro/files/file/152-homebrew-app-store-switch/
 -  https://wiki.gbatemp.net/wiki/List_of_Switch_homebrew_applications

They are also referenced in popular set-up guides that I have used as well:
 - https://nh-server.github.io/switch-guide/user_guide/emummc/sd_preparation/
 - https://wiiu.hacks.guide/#/haxchi/sd-preparation

Looking through more I did finally see mention of the other one, maybe after since I followed the guide?:
 - https://3ds.hacks.guide/finalizing-setup
 - https://dsi.cfw.guide/

Maybe I passed over it since the name presents handling update concerns, and I was already doing that manually at the time using USB, SD, or FTP methods.

To better complete by adding links that I just found:
 - https://github.com/Universal-Team/Universal-Updater
 - https://db.universal-team.net/ds/

Seems it supports some of the older platforms, so they almost complement each other.

I guess it could be added to both.

**Comment by Core-2-Extreme** [comment]
added
