### ISSUE TITLE
can't read .mpg /.vob file

### ISSUE THREAD

**Issue by JoeBonziXP** [Core-2-Extreme/Video_player_for_3DS#40]
i get an error when i try to play an mpg file i took from a dvd, mpeg2 and ac3 audio codec should be supported, mpeg4/xvid files work fine
i'm using old 3ds

**Comment by JustScratchCoder** [comment]
From my experience. The mpg files don't work. You need to convert the mpg file to mp4. But with these settings. Video codec: MPEG1VIDEO  Audio Codec: mpeg 2.   And The quality 360p.

**Comment by JoeBonziXP** [comment]
thank you
