### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by samisathenaaa** [Core-2-Extreme/Video_player_for_3DS#43]
![2022-02-23_14-55-47 444_bot](https://user-images.githubusercontent.com/98918932/155158804-bc97b8d3-216d-4a0f-9a6c-056210585741.png)

**Comment by Core-2-Extreme** [comment]
If you are using OLD3DS, it doesn't have enought memory.
If you are using NEW3DS, video may be loaded in next version but it may not run at full speed.
Seek [recommended resolution](https://github.com/Core-2-Extreme/Video_player_for_3DS#recommended-resolution) for more info.
