### ISSUE TITLE
Brightness control using d-pad?

### ISSUE THREAD

**Issue by moisespr123** [Core-2-Extreme/Video_player_for_3DS#44]
Hi, just wondering if there's a chance we could control the screen brightness by using some key like the d-pad up/down when in full screen mode. It would be wonderful instead of going to the settings to adjust it.

Thanks a lot for this homebrew!!

**Comment by Core-2-Extreme** [comment]
ok, I'll add it (but not only in full screen mode).
Thank you for your suggestion.

**Comment by Core-2-Extreme** [comment]
Added
