### ISSUE TITLE
Move the video and Zoom functions do not work.

### ISSUE THREAD

**Issue by lkchx123** [Core-2-Extreme/Video_player_for_3DS#45]
I use the arrow keys and L/R, but nothing happened. 
There seems to be no such problem in previous versions.

**Comment by Core-2-Extreme** [comment]
You may turned "disable move video" on.
Please check it and let me know if it helped.

**Comment by lkchx123** [comment]
> You may turned "disable move video" on. Please check it and let me know if it helped.

Thanks for your help. I once set it, but then forgot that the setting interface can be slidden down.
