### ISSUE TITLE
Crash with latest master (aab57fc) on New 2DS XL

### ISSUE THREAD

**Issue by Yrouel** [Core-2-Extreme/Video_player_for_3DS#46]
After your latest fix I managed to compile this on my Mac however both the 3dsx and the cia versions crash on my N2DSXL with latest firmware and Luma.

[crash_dumps.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8261661/crash_dumps.zip)

![cia_crash](https://user-images.githubusercontent.com/70481880/158580453-5b38aef0-539f-40df-af02-03a9eaa4c0f6.jpeg)
![3dsx_crash](https://user-images.githubusercontent.com/70481880/158580522-5842c7ad-8128-4671-a6f9-718a5e729ac6.jpeg)

**Comment by Core-2-Extreme** [comment]
For me it worked on NEW3DS and OLD3DS. (I don't have NEW2DS)
According to your crash dump, it might crash around https://github.com/Core-2-Extreme/Video_player_for_3DS/blob/main/source/system/setting_menu.cpp#L303
so can you remove that line and check if it crashs?
If it crashs, please send me crash dump once more.

**Comment by Yrouel** [comment]
Still crashes

[crash_dump_00000000.dmp.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8261938/crash_dump_00000000.dmp.zip)


![IMG_6985](https://user-images.githubusercontent.com/70481880/158587035-ace87535-5220-4079-b812-f8d0fafa7604.jpeg)

**Comment by Core-2-Extreme** [comment]
ok, then run
`[your_devkitPro_folder]\devkitARM\bin\arm-none-eabi-gdb [path/to/Video_player_for_3DS.elf]`
on your computer.
Then open luma menu on your 3DS and go to debugger options -> select enable debugger -> select force debug next application -> close luma menu -> run video player for 3ds
on your computer type `target remote [your 3ds local IP address]:4003` after it connects, type `c` to continue you should see `Segmentation fault` message then type `info thread` and `bt` to get informations finally type `quit` to quit.

Send entire logs here.

**Comment by Yrouel** [comment]
Ok I did everything and this is all the shell output, if there are actual .log files I haven't found them

[shell.txt](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8262493/shell.txt)

**Comment by Core-2-Extreme** [comment]
It crashes exactly at [setting_menu.cpp:303](https://github.com/Core-2-Extreme/Video_player_for_3DS/blob/main/source/system/setting_menu.cpp#L303)
Did you comment out it?

**Comment by Yrouel** [comment]
Yes I run the cia version both ways I attached both debug logs

**Comment by Core-2-Extreme** [comment]
Oh, sorry I have missed it.
Then, comment [line 1225 and 1226](https://github.com/Core-2-Extreme/Video_player_for_3DS/blob/main/source/system/draw/draw.cpp#L1225) out and try again.

**Comment by Yrouel** [comment]
Hey so I got it working. I simply cloned again latest master and replaced libctru.a and libctrud.a with the versions I had already installed as part of devkitpro (libctru 2.1.0-1).

Perhaps consider not duplicating stuff in your repo that already exists as part of the "standard" devkitpro/devkit arm toolchain

**Comment by Core-2-Extreme** [comment]
I'm using custom libctru so using standard libctru results in being not working some functions.

**Comment by Core-2-Extreme** [comment]
Source code is [here](https://github.com/Core-2-Extreme/libctru)
If you compile it and use that one, will it work for you?

**Comment by Yrouel** [comment]
It crashes

(the crash dump is from the 3dsx)

[crash_dump_00000001.dmp.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8276186/crash_dump_00000001.dmp.zip)

[debug_compiled_custom_libctru.txt](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8276193/debug_compiled_custom_libctru.txt)

**Comment by Core-2-Extreme** [comment]
Before you type quit, type `p util_log_logs` to get internal logs.
And send entire logs here (it will be LONG logs, if gdb asks `--Type <RET> for more, q to quit, c to continue without paging--` you can type `c`)

**Comment by Yrouel** [comment]
[ALL THE LOGS.txt](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8277005/ALL.THE.LOGS.txt)

**Comment by Core-2-Extreme** [comment]
Use the newest commit and repeat the same steps.

**Comment by Yrouel** [comment]
Well it's working now. Plain simple compile from latest master, I didn't even replace libctru with the recompiled custom one

**Comment by Core-2-Extreme** [comment]
So do you mean the newest commit (62d99b5) is working but aab57fc is not working?
If so I only changed log related code so it shouldn't change behaviour.
If you clone the newest commit and rollback [changes](https://github.com/Core-2-Extreme/Video_player_for_3DS/commit/62d99b51ca9836126236183ad37d5c76478e8a83) manually, what will happen?

**Comment by Yrouel** [comment]
Now even aab57fc is working. I have no idea what I did differently to be honest, perhaps having updated Luma helped?

**Comment by Yrouel** [comment]
It doesn't crash even with old Luma now... I really don't know what's going on and now I'm sorry to have bothered you

**Comment by Yrouel** [comment]
This is interesting so I did a checkout of cf67e99 to verify that indeed that one still didn't compile (still didn't) then I did make clean and checkout 02568be which did compile fine...and started crashing again.
I'm sure what's going on but I suspect make clean doesn't actually completely clean everything and that causes issues.
When it started working I had done a completely fresh clone when now that I think about it when it was crashing I was using make clean in between tries.
I deleted the folder and cloned it fresh, same checkout, and it works. I'm attaching both 3dsx builds

[Video_player_for_3DS_GOOD-BAD_02568be.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8284268/Video_player_for_3DS_GOOD-BAD_02568be.zip)

**Comment by Core-2-Extreme** [comment]
I reproduced your situation by using make clean and I found that it cleans **too much** even necessary files.
I updated make file and it should work now with make clean.

**Comment by Yrouel** [comment]
Ok yeah I jumped around again with builds and it works now, thanks.

Slightly related: can you make it so it uses by default makerom and bannertool from the PATH?

**Comment by Core-2-Extreme** [comment]
I changed it so.

**Comment by Yrouel** [comment]
Awesome thank you very much.
Just did a "final" fresh clone and build with this last commit and it works fine.
I guess you can close this (it was quite the head-scratcher I think)
