### ISSUE TITLE
Frame desync in 3D videos

### ISSUE THREAD

**Issue by MediumNight** [Core-2-Extreme/Video_player_for_3DS#47]
I found the file to the video, but when i click a on it it tells me 

Error Out of linear memory
Description:

Place:
Vid\Decode Thread
Error code:
0xfffffffd

**Comment by Core-2-Extreme** [comment]
What is your video resolution?
Maybe you are trying to play too high resolution video.
See [recommended resolution](https://github.com/Core-2-Extreme/Video_player_for_3DS#recommended-resolution) for more info.

**Comment by jean-raphael** [comment]
same problem with mpeg1 and mpeg2 

i use this script : 

`
::scale video to 800*240p
ffmpeg\bin\ffmpeg.exe -i %1 -vf scale=800:240:flags=neighbor -c:v h264_nvenc -maxrate 100M -b:v 12M -minrate 6M scaled.mkv 

::split left and right
ffmpeg\bin\ffmpeg.exe -i scaled.mkv -filter_complex "split[l][r];[l]stereo3d=sbsl:ml[left];[r]stereo3d=sbsl:mr[right]" -map [left] -map 0:a -c:a copy left.mkv -map [right] -map 0:a -c:a copy right.mkv

::create 4 folders
mkdir 1
mkdir 2
mkdir 3
mkdir 4

::cut video to max size of 0:40:00
ffmpeg\bin\ffmpeg.exe -to 0:40:00 -i right.mkv -c:v copy -c:a copy .\1\right.mkv
ffmpeg\bin\ffmpeg.exe -to 0:40:00 -i left.mkv -c:v copy -c:a copy .\1\left.mkv

::cut from 40 to 1,20
ffmpeg\bin\ffmpeg.exe -ss 0:40:00 -to 1:20:00 -i right.mkv -c:v copy -c:a copy .\2\right.mkv
ffmpeg\bin\ffmpeg.exe -ss 0:40:00 -to 1:20:00 -i left.mkv -c:v copy -c:a copy .\2\left.mkv

::cut from 1,20 to 2,0
ffmpeg\bin\ffmpeg.exe -ss 1:20:00 -to 2:00:00 -i right.mkv -c:v copy -c:a copy .\3\right.mkv
ffmpeg\bin\ffmpeg.exe -ss 1:20:00 -to 2:00:00 -i left.mkv -c:v copy -c:a copy .\3\left.mkv

::cut from 2,0 to 2,4
ffmpeg\bin\ffmpeg.exe -ss 2:00:00 -to 2:41:00 -i right.mkv -c:v copy -c:a copy .\4\right.mkv
ffmpeg\bin\ffmpeg.exe -ss 2:00:00 -to 2:41:00 -i left.mkv -c:v copy -c:a copy .\4\left.mkv

:: merge Left and right into a 800*240p video
::-b:v 2M
ffmpeg\bin\ffmpeg.exe -i .\1\left.mkv -i .\1\right.mkv -map 0:v:0 -map 0:a:0 -map 1:v:0 -vcodec mpeg2video -r 30 -q:v 15 -ac 2 movie_Part_1.avi
ffmpeg\bin\ffmpeg.exe -i .\2\left.mkv -i .\2\right.mkv -map 0:v:0 -map 0:a:0 -map 1:v:0 -vcodec mpeg2video -r 30 -q:v 15 -ac 2 movie_Part_2.avi
ffmpeg\bin\ffmpeg.exe -i .\3\left.mkv -i .\3\right.mkv -map 0:v:0 -map 0:a:0 -map 1:v:0 -vcodec mpeg2video -r 30 -q:v 15 -ac 2 movie_Part_3.avi
ffmpeg\bin\ffmpeg.exe -i .\4\left.mkv -i .\4\right.mkv -map 0:v:0 -map 0:a:0 -map 1:v:0 -vcodec mpeg2video -r 30 -q:v 15 -ac 2 movie_Part_4.avi

:: remove folders and files
::rmdir /Q /S 1
::rmdir /Q /S 2
::rmdir /Q /S 3
::rmdir /Q /S 4

::remove left and right files
::del right.mkv
::del left.mkv
::del scaled.mkv`

**Comment by Core-2-Extreme** [comment]
I couldn't reproduce out of memory error, but I noticed that video is not played at correct speed.
I created new issues for this #48

**Comment by jean-raphael** [comment]
Ok I Have Test the exact same script on a different videos, and i d'ont have the memory error,

**Comment by jean-raphael** [comment]
How can I send you my video without making it available to everyone

**Comment by Core-2-Extreme** [comment]
Send me your video file link on my Discord : ARM11#7410

**Comment by jean-raphael** [comment]
done ! i send it to you

**Comment by Core-2-Extreme** [comment]
I fixed it, confirm that it actually fixed.
[Video_player_for_3DS.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/8883251/Video_player_for_3DS.zip)
