### ISSUE TITLE
Does not work on Citra emulator

### ISSUE THREAD

**Issue by MInecrafterPictures** [Core-2-Extreme/Video_player_for_3DS#53]
I tried the homebrew on Citra (3DS emulator) and it only got me a black screen.
I wonder if you can make a Citra-optimised version on your program or if Citra developers need to patch it up for your homebrew to function?

**Comment by Core-2-Extreme** [comment]
Is Citra NEW3DS emulator or OLD3DS?
I'm not sure, but I suspect Citra may not support hardware decoder, hardware color converter and/or DMA.

**Comment by MInecrafterPictures** [comment]
I'm aiming towards New 3DS emulation while using Citra

**Comment by Core-2-Extreme** [comment]
ok then try disabling hardware decoder in settings (Press Y button in video player, select second tab, tap on use hardware decoder).
If it won't help, disable hardware color conversion.

**Comment by MInecrafterPictures** [comment]
You can try diagnosting the black screen issue by yourself using the latest version of Citra Canary and Citra Nighty if you want to make this functional for Citra emulation

**Comment by Core-2-Extreme** [comment]
ok, I checked it on citra and realized that I got it wrong what you mean by 'black screen'.
After investigating, it seems citra doesn't support necessary APIs and is not able to support it easily.
So I decided to not to support it right now although I may support it at some point.

If you still want to use it on emulator, use vvctre emulator that I sometimes use for debugging.
[Video_player_for_3DS.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/9960693/Video_player_for_3DS.zip)

**Comment by MInecrafterPictures** [comment]
Vvctre is now on the Internet Archive due ot OG creator of that Citra fork deleted that, so I'm just going to try the dev build using Citra.
It ain't working, Vvctre it is.
Btw thanks for at least trying to make the homebrew Citra-compatible! Kudos to you, Citra users like me can finally use it once the fix is up!

**Comment by Core-2-Extreme** [comment]
I have vvctre 50 or something and works on it.
I'll upload the copy later.

**Comment by Core-2-Extreme** [comment]
Use this vvctre. : [vvctre_51.0.3.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/9980710/vvctre_51.0.3.zip)

To use video player, you need to change some settings.

1. Settings menu (right bottom) -> Advanced settings -> Set use fake model to `OLD2DS`.
2. Open video player (left top) -> Press Y button -> Select second tab -> disable `multi threaded decoding` and `hardware color conversion`.
3. Restart it.(Don't use Windows's close button, click on `▽` icon in app)

**Comment by MInecrafterPictures** [comment]
Tried to open the homebrew directly from the emulator. Just crashed the emulator.
Also I can't seem to find anything that modifies which 3DS is Vvctre emulating before I even start emulation.
I just don't see any option in the emulator's menu.
You can try using a virtual machine using the same emulator and development build of the homebrew if you want to double check.
If it can be fixed, is there any way to do it?

**Comment by Core-2-Extreme** [comment]
It works on my side, are you able to use at least one different app on vvctre?

**Comment by MInecrafterPictures** [comment]
I extracted your copy of Vvctre and overwrite the one I found.
I think the problem with me emulating the homebrew using the matching emulator as you is that I don't know where are the settings to change the 3DS emulation between old and new 3DS since I see nothing about it in the main interface itself.
Maybe because some of the emulation settings are stored in Roaming Appdata, Local Appdata or the Documents folder? I don't know.

**Comment by Core-2-Extreme** [comment]
>  I don't know where are the settings to change the 3DS emulation between old and new 3DS since I see nothing about it in the main interface itself.

You need to change settings in my app not vvctre UI.

> Maybe because some of the emulation settings are stored in Roaming Appdata, Local Appdata or the Documents folder? I don't know.

I think settings are saved in `{vvctre_foloder}\user\nand\*`.

So try to delete settings first and try again.
If it won't help please send me vvctre logs (cmd outputs).

**Comment by M4x0udev** [comment]
can some one please explain to me why on earth would one use a 3ds emulator + 3ds video player to watch a video on windows/android ? ^^'
