### ISSUE TITLE
keep stopping and going😐

### ISSUE THREAD

**Issue by trapgod2008** [Core-2-Extreme/Video_player_for_3DS#57]
the software keep saying processing while the video is playing. And while it´s playing it´s keep stopping an going and it is annoying. so can some one find the problem and try to fix it probably try to get a better update

**Comment by Core-2-Extreme** [comment]
You may be trying to play the video that has too high resolution or framerate.
Did you check [Recommended resolution](https://github.com/Core-2-Extreme/Video_player_for_3DS#Recommended-resolution)?

**Comment by Core-2-Extreme** [comment]
Take a look at [prepeare videos](https://github.com/Core-2-Extreme/Video_player_for_3DS#Prepare-videos)

**Comment by Nakoju** [comment]
No idea if this is the same problem, though I seem to be having the same processing issue with some movies. I have 2 movies both made with nvc, though one runs fine and the other processes frequently.
