### ISSUE TITLE
VobSub subtitle support

### ISSUE THREAD

**Issue by xxmichibxx** [Core-2-Extreme/Video_player_for_3DS#58]
Please add subtitle support for VobSub (zlib) encoded subtitles.

**Comment by Core-2-Extreme** [comment]
Can you share me an example vobsub file so that I can test?
I failed to find a good example file.

**Comment by xxmichibxx** [comment]
Sure. Here is a clip (3min) for the new 3DS.
[vobsub_sample_new3DS.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/12295351/vobsub_sample_new3DS.zip)

**Comment by Core-2-Extreme** [comment]
Supported it.
It works on the file you provided.
If you have other videos that have vobsub, can you test them?

(This is nightly build, next release will support it officially)
[Video_player_for_3DS.zip](https://github.com/Core-2-Extreme/Video_player_for_3DS/files/12344915/Video_player_for_3DS.zip)

**Comment by xxmichibxx** [comment]
Works perfectly fine, thanks!

**Comment by xxmichibxx** [comment]
Works perfectly fine, thanks a lot!
