### ISSUE TITLE
Is there a video duration limit?

### ISSUE THREAD

**Issue by DuckersMcQuack** [Core-2-Extreme/Video_player_for_3DS#67]
I can compress my movies easily down to 2GB in X265 for my phone, so way higher bitrate is easy for 240-480p videos. Question is before i start looking for machines and cables, can it easily play a full length movie?

**Comment by Core-2-Extreme** [comment]
> Question is before i start looking for machines and cables, can it easily play a full length movie?

There is no specific limit, however longer video may cause out of memory error especially on OLD 3DS.
If you use .mkv container, this problem usually won't happen. (I can play 4 hours+ video (H.264 480p video with .mkv) on my NEW 3DS easily)

> I can compress my movies easily down to 2GB in X265 for my phone, so way higher bitrate is easy for 240-480p videos.

See [here](https://github.com/Core-2-Extreme/Video_player_for_3DS#recommended-resolution) for recommended resolutions.
