### ISSUE TITLE
Screen capture doesn't work at all

### ISSUE THREAD

**Issue by obscurerev** [Core-2-Extreme/Video_player_for_3DS#9]
The screen capture feature doesn't work at all. It crashes upon pressing either of the 3 options. I might be unaware that it doesn't do anything and is probably an experimental feature.

**Comment by Core-2-Extreme** [comment]
Are you using old 3ds or new 3ds?

**Comment by obscurerev** [comment]
I am using a new 2ds xl

**Comment by Core-2-Extreme** [comment]
Give me crash dump
